### ISSUE TITLE
How do you run this project ?

### ISSUE THREAD

**Issue by Tanneguy** [huytd/kanelm#1]
Hi, I am learning Elm and not aware of all the tricks to run actual projects.
Would you add in the README.md how to run kanelm locally ?

I have tried to install webpack and run `webpack -p`. It produces `dist/dist.js` with some errors afterwards: 

```
ERROR in ./src/main.js
Module not found: Error: Can't resolve 'elm-webpack-loader' in '/home/..../kanelm'
 @ ./src/main.js 4:12-33

ERROR in ./src/main.js
Module not found: Error: Can't resolve 'file-loader' in '/home/..../kanelm'
 @ ./src/main.js 1:0-23

ERROR in ./src/main.js
Module not found: Error: Can't resolve 'style-loader' in '/home/..../kanelm'
 @ ./src/main.js 2:0-22

```

**Comment by SidneyNemzer** [comment]
*This assumes you have Git, NPM, and elm installed globally on your computer*

1. Clone the project with Git
2. Open the directory that you cloned the project into
3. Run `npm install` to install NPM packages
4. Run `elm package install` to install Elm packages
5. Run `npm start`. This script (defined in `package.json`) starts the `webpack-dev-server`
6. Open your browser and go to `localhost:3000`

In case you were wondering, the errors that you got say that several "modules" are missing, which indicates that you didn't run `npm install`.

**Comment by huytd** [comment]
Sorry for being lazy, let me put some instruction to README.md :D

**Comment by Tanneguy** [comment]
Thank you !



2017-12-15 22:11 GMT+01:00 Huy Tr. <notifications@github.com>:

**Comment by Tanneguy** [comment]
Thank you !


2017-12-15 21:07 GMT+01:00 Sidney Nemzer <notifications@github.com>:
